### ISSUE TITLE
Reuse Iteration Number

### ISSUE THREAD

**Issue by Weilandator** [blazar-ts/soup_tools#15]
I get an error page when I try to pull TXT files with the same iteration number...

ie, I'll pull with iteration 1, notice something i need to change... load/change data and need to pull another iteration 1 but can't...

**Comment by weilandia** [comment]
Hey man, I'll try to get to these tickets this wk.  Sry!

**Comment by weilandia** [comment]
Cant recreate.

**Comment by weilandia** [comment]
@Weilandator
