### ISSUE TITLE
Add option to download template upload

### ISSUE THREAD

**Issue by weilandia** [blazar-ts/soup_tools#27]

**Comment by weilandia** [comment]
[SEWP V TR.xlsx](https://github.com/blazar-ts/soup_tools/files/1051122/SEWP.V.TR.xlsx)

**Comment by Weilandator** [comment]
This file just needs to be visible on the TR Dashboard somewhere - Let me know when you do this and I'll send you the most current template.  OR if there is a place that I can load it, great.

**Comment by weilandia** [comment]
This is done.  You have to add a template for each org under the sys_admin settings tab @Weilandator
