### ISSUE TITLE
Rename Blazar to DRS for the Orgs

### ISSUE THREAD

**Issue by Weilandator** [blazar-ts/soup_tools#31]

**Comment by weilandia** [comment]
@Weilandator What does this mean?

**Comment by Weilandator** [comment]
We need another org - epoch Anacapa DRS

Mike

[cid:image002.png@01D297FF.AD61D410]Michael Weiland
Head of Operations
Blazar Technology Solutions<http://blazar-ts.com/>
C: 775-815-2120<tel:775-815-2120>


The information contained in this communication is confidential, may constitute inside information, is intended only for the use of the addressee, and is the property of Blazar Technology Solutions LLC. Unauthorized use, disclosure or copying of this communication or any part thereof is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by return e-mail and destroy this communication and all copies thereof, including all attachments.

On Jul 30, 2017, at 13:10, Nick Weiland <notifications@github.com<mailto:notifications@github.com>> wrote:


@Weilandator<https://github.com/weilandator> What does this mean?
