### ISSUE TITLE
Stale TR Addition

### ISSUE THREAD

**Issue by Weilandator** [blazar-ts/soup_tools#34]
Is it possible to not allow a new draft TR if there is a Stale TR?  

I want the team to finish and/or complete the stale one before moving onward.

**Comment by weilandia** [comment]
That seems overly opinionated... Are you sure that's the way to go?

**Comment by Weilandator** [comment]
Open to suggestions- we had an issue we are looking to avoid... a stale TR wasn't processed and a new one generated, the stale was ignored and we didn't get it on contract in time...

Mike

[cid:image002.png@01D297FF.AD61D410]Michael Weiland
Head of Operations
Blazar Technology Solutions<http://blazar-ts.com/>
C: 775-815-2120<tel:775-815-2120>


The information contained in this communication is confidential, may constitute inside information, is intended only for the use of the addressee, and is the property of Blazar Technology Solutions LLC. Unauthorized use, disclosure or copying of this communication or any part thereof is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by return e-mail and destroy this communication and all copies thereof, including all attachments.

On Aug 2, 2017, at 23:36, Nick Weiland <notifications@github.com<mailto:notifications@github.com>> wrote:


That seems overly opinionated... Are you sure that's the way to go?

**Comment by weilandia** [comment]
@Weilandator should this be team-wide or specific to the person who created the stale one?

**Comment by Weilandator** [comment]
Team wide
