### ISSUE TITLE
Change Download File name for all TR

### ISSUE THREAD

**Issue by Weilandator** [blazar-ts/soup_tools#52]
Naming convention is:

TR + Date Stamp + Sequence Number + First letter of org (A, E, D, G)"

"TR201711100001A"

**Comment by Weilandator** [comment]
Can you also specify download locations or is this a computer/application setting?

**Comment by Weilandator** [comment]
Can you reopen this one?

**Comment by Weilandator** [comment]
Just adding color (be sure to read all the way down before you start):

We take this file and download it  the default download place.  We then open a new email and send it to "sewpvtr@nasa.sewp.gov" with just the file attached and the subject line being the name above. Naming convention is:
TR201825050001A
for example as the TR file for today from Anacapa.

Can you specify the download location for this file for everyone's desktop?  Or is that a computer setting?

ALSO-----

The naming convention needs to be updated as stated above but the download location is OBE if we can get SoupTools to send the email for us -- See backlog #42.

**Comment by weilandia** [comment]
OBE??

We can get souptools to send the email and we cannot specify the download location.  I'll do the name change for this ticket and start the other stuff in #42 when we get to it.
